### ISSUE TITLE
Restructure pymontecarlo

### ISSUE THREAD

**Issue by ppinard** [pymontecarlo/pymontecarlo#15]
This is a general issue to discuss improvements to pymontecarlo and take the time to clearly define the goals of this program.

Looking back at my initial design of pymontecarlo, I think there are some serious shortcomings that need to be addressed and rethought. Here is a list I came up with after observing users during the Monte Carlo workshop in Aachen and from discussions with @drix00  and @silrichter. I also propose some solutions.

1. Whether it is expert and beginner users, Monte Carlo simulations are usually used in EPMA with a clear goal in mind, e.g. calculate intensities/k-ratios, evaluate the size of the interaction volume, obtain a spectrum to compare with experimental results, etc. This usually involves running more than one simulation (different accelerating voltage, sample composition, etc.). This is something that is currently not easy to do in pymontecarlo. Most of the post-calculations have to be done manually. 

I propose to create a class *Task*. Each *Task* would have a clear objective, e.g. calculate k-ratios. The class would ensure that the simulated options can meet this objective. After the simulations, it will collect the results and calculate new ones based on that objective.

```
class Task:

    def apply(self, list_options):
        raise NotImplementedError

    def calculate(self, list_options):
        raise NotImplementedError

    @property
    def results(self):
        raise NotImplementedError
```

2. The file format, XML for options and HDF5 for results, is confusing. I propose to only used HDF5 and save the options either as attribute or in special datasets. I also propose to create the extension `.mcoptions` instead of `.h5`.

3. The class *Options* has currently two roles: to create several simulations by adding parameters, e.g. different beam energies, and to store the parameter of a single simulation. I propose to separate these roles, creating an *OptionsBuilder* for the first role and simplying the Options to only store the parameters for a single simulation.

4. I would rename the *Geometry* class to *Sample* for clarity.

5. I would take the expansion operation out of the *Converter* class. The expansion is to convert a series of parameters into a list of *Options*. This is often specific to each MC program and it should be part of the *OptionsBuilder*.

6. I would remove the class *Results* and *ResultsContainer*, and simply stores the results inside the *Options*. An *Options* that has not been simulated would simply have no results. 

7. In pymontecarlo, a *Detector* corresponds to a virtual detector and not a physical one that would be attached to an electron microscope. Each *Detector* is expected to yield one *Result*. Although I would keep this philosophy, I think the current detector definition could be simplified. For instance, the *PhotonIntensityDetector* is responsible for storing the generated and emitted intensities. This should be two detectors. Subpackages should be used to separate different types of detectors, instead of having all of them in the module `pymontecarlo.options.detector`.

8. It is important that once a simulation was executed, that its options cannot be modified. It is currently done by the concept of **freezing**. I think the whole structure of pymontecarlo could be simplified if the *Options* class and all its components (e.g. beam, sample, detectors, limits, etc.) would be immutable. To prevent having too many arguments in the `__init__` we could create *Builder* classes instead. While complete immutability is difficult to implement in Python, I would propose to either use the metaclass trick of pyxray ([pyxray.cbook.Immutable](https://github.com/ppinard/pyxray/blob/sql/pyxray/cbook.py#L14)).

9. A missing functionality of pymontecarlo is the ability to use other parameters of an option to define a new one. For instance, it should be possible to easily set the maximum energy of an ED spectrum to the beam energy. I propose to create the following interface:

```
class Lazy:

    def resolve(self, options):
        raise NotImplementedError
```

Upon the creation of an *Options* object, the `resolve` method should be called.

10. I would remove the use of namespaces (`pymontecarlo.program.casino`, `pymontecarlo.program.monaco`, etc.) and instead use longer root package (`pymontecarlo_casino`, `pymontecarlo_monaco`, etc.) as it was done for pyHMSA.

11. The distribution of pymontecarlo to the different operating system (Windows, MacOS, Linux) is quite complicated due to several factors. 

  - First, it is difficult to freeze (i.e. include the Python distribution) due to the use of setuptools' entry points. These entry points are however essential to allow pymontecarlo to discover installed programs, handlers to parse XML or HDF5 results, GUI interfaces, etc. [py2exe](py2exe.org), [py2app](https://pythonhosted.org/py2app/), [cx_freeze](https://cx-freeze.readthedocs.io/en/latest/) do not support [entry points](http://docs.python-guide.org/en/latest/shipping/freezing/#comparison-of-freezing-tools). For Windows, the project [python_embedded_launcher](https://github.com/zsquareplusc/python-embedded-launcher) works well, but I did not find alternative to MacOS and Linux.

  - Secondly, it is not clear up to now whether pymontecarlo should distribute the Monte Carlo program or ask the user to download/install them separately. I propose that we provide all freely available MC programs with pymontecarlo and configure pymontecarlo accordingly to use them. These would include Casino, WinXRay, PENEPMA, NISTMonte and MONACO. For PENEPMA, I think we should only support the version distributed by the Barcelona group.

  - Thirdly, to facilitate installation, it should be possible to run pymontecarlo directly after extracting it from a ZIP, i.e. no installation, no administrative rights. On Linux, we can probably assume that Python 3 is installed. This assumption should not be made for Windows and MacOS.

Finally here is some class definitions for the above proposals:
![pymontecarlo](https://cloud.githubusercontent.com/assets/715280/20041988/fb3ede32-a469-11e6-9707-6befa66714a1.png)

**Comment by drix00** [comment]
Some of my comments below, but first maybe we should create a wiki of the proposal so we can add comment and modification in it with a history of all change.

> 2 The file format, XML for options and HDF5 for results, is confusing. I propose to only used HDF5 and save the options either as attribute or in special datasets. I also propose to create the extension .mcoptions instead of .h5.

Using HDF5 file, you don't have separate option file and result file. You have one file with option and possibly result in it. Also you can add analysis, i.e., different analysis of the simulation results without redoing the simulations.

> 6 I would remove the class Results and ResultsContainer, and simply stores the results inside the Options. An Options that has not been simulated would simply have no results.

I am not sure to understand this point. For me options and results are different and not in the same class. Maybe a simulation (single) class containing the options and results class.

> 8 It is important that once a simulation was executed, that its options cannot be modified. It is currently done by the concept of freezing. I think the whole structure of pymontecarlo could be simplified if the Options class and all its components (e.g. beam, sample, detectors, limits, etc.) would be immutable...

Can you give an example why the Options class need to be immutable? I understand we need a way to tell in the hdf5 file if the option associate with a results change (with a check sum maybe). But I never have to worry in the code about the Options class changing during the simulation or after.

> 9 A missing functionality of pymontecarlo is the ability to use other parameters of an option to define a new one. For instance, it should be possible to easily set the maximum energy of an ED spectrum to the beam energy.

Maybe have a look at lmfit code how it deal with parameters and equation of parameters in the fit model and constraints which is similar to what we need pymontecarlo to do.

> 10 I would remove the use of namespaces (pymontecarlo.program.casino, pymontecarlo.program.monaco, etc.) and instead use longer root package (pymontecarlo_casino, pymontecarlo_monaco, etc.) as it was done for pyHMSA.

Do you have a link or example, I did not find it in pyHMSA code.

> 11 The distribution of pymontecarlo to the different operating system (Windows, MacOS, Linux) is quite complicated due to several factors.

This one is a big challenge. I need to study it more, but my first question is setuptool entry point is the only solution?

**Comment by ppinard** [comment]
I would propose to discuss of the changes here and once we agree we can move the final decision to the wiki. I don't think it is easy to have a discussion over the wiki.

To answer your questions and comments,

> 6. I am not sure to understand this point. For me options and results are different and not in the same class. Maybe a simulation (single) class containing the options and results class.

In the current version, _Results_ contains the _options_ with all the different parameters (e.g. different beam energies) and some _ResultsContainer_'s for the results of each simulation (one for each beam energy). 

I agree we should have another class called _Simulation_ that would contains _Options_ (new version with all single parameters, see point 3), _Results_ and maybe other things like results for a re-analysis or some program information (version, etc.). In short,

```
Simulation:
    options -> Options
    results -> Results
    ...
```

> 8. Can you give an example why the Options class need to be immutable?

I think it is important that an _Options_ is validated before being run by a MC program. It would be frustrating to setup some options and then realized that they cannot be run. My idea was therefore that an _Options_ is validated upon its construction (i.e. in the `__init__(...)`) and is never changed afterwards. Something like this:

```python
class Options:

    def __init__(self, program, beam, sample, ...):
        self.program = program
        self.beam = program.converter.convert_beam(beam)
        self.sample = program.converter.convert_sample(sample)
        ...
```

I guess the other way would be to add a method `validate()`, but that would mean that each _Beam_, _Sample_, _Detector_ should also take a `program` object in order to validate their parameter.

> 9. Maybe have a look at lmfit code how it deal with parameters and equation of parameters in the fit model and constraints which is similar to what we need pymontecarlo to do.

I know the lmfit special syntax, but I must admit I don't really like using strings to define relationships between objects. [sympy](http://docs.sympy.org/latest/tutorial/basic_operations.html) seems to have a more sophisticated way to handle this.

> 10. Do you have a link or example, I did not find it in pyHMSA code.

The main project: https://github.com/pyhmsa/pyhmsa
and some other projects where the root package is `pyhmsa_{name}`:
https://github.com/pyhmsa/pyhmsa-gui
https://github.com/pyhmsa/pyhmsa-tiff

Removing namespaces also goes in line with point 11, as they are more difficult to support for frozen distribution.

> 11. I need to study it more, but my first question is setuptool entry point is the only solution?

No, and it can probably be replaced by something else. Entry points are stored in a config file in the .egg-info or .dist-info folder. setuptools is only intelligent to know where to find them. For us, we could put everything in a config file and import the entry points from there.

My proposal for the different distributions would be to create a "debug" project where we have numpy, scipy, matplotlib and pyQt as dependencies and try to create distributions for all the platforms.

**Comment by drix00** [comment]
> I would propose to discuss of the changes here and once we agree we can move the final decision to the wiki. I don't think it is easy to have a discussion over the wiki.

Maybe create separate issue for each item, but keep the main issue? It will be difficult to follow the discussion through multiple items in a series of comments. I think you can modify the original post to add link to each issue.

**Comment by ppinard** [comment]
Very good idea. I moved all items and discussions to individual issues. They all have the milestone [1.0](https://github.com/pymontecarlo/pymontecarlo/milestone/1)

**Comment by drix00** [comment]
I just found we can create a project for the pymontecarlo organization and include/add notes and issues. I have create one for this issue and add the 11 issues. I did not find a way to create a link, but you can find it on the pymontecarlo organization projects page or try this link https://github.com/orgs/pymontecarlo/projects/1.
