### ISSUE TITLE
Remove XML and store options and results in HDF5

### ISSUE THREAD

**Issue by ppinard** [pymontecarlo/pymontecarlo#16]
The file format, XML for options and HDF5 for results, is confusing. I propose to only used HDF5 and save the options either as attribute or in special datasets. I also propose to create the extension .mcoptions instead of .h5.

**Comment by ppinard** [comment]
@drix00 said: 
Using HDF5 file, you don't have separate option file and result file. You have one file with option and possibly result in it. Also you can add analysis, i.e., different analysis of the simulation results without redoing the simulations.

**Comment by ppinard** [comment]
Based on #21 and #17 , I would propose the following structure for the HDF5 file. I added in parenthesis the HDF5 type (i.e. group, dataset, attribute).

- Simulations (group)
  - Simulation 1 (group)
    - Options (group)
      - program (attribute)
      - beam (empty dataset)
        - energy (attribute)
        - ...
      - sample (empty dataset)
      - ...
    - Results (group)
      - Result 1 (group)
        - Data 1 (dataset)
        - Data 2 (dataset)
        - ...
       - Result 2 (group)
      - ...
  - Simulation 2 (group)
  - ...
- Tasks (group)
  - Task 1 (group)
    - Results (group)
      - Result 1 (group)
        - Data 1 (dataset)
        - Data 2 (dataset)
        - ...
       - Result 2 (group)
      - ...
  - Task 2 (group)
  - ...

**Comment by ppinard** [comment]
Based on the goal to first create an interface to simulate k-ratios (#33), how could we save X-ray intensities and then k-ratios inside a HDF5 dataset? Keeping in mind that some programs return intensities for X-ray transition (e.g. Ka1 / K-L3), X-ray line (e.g. Ka) or X-ray series (e.g. K).

**Comment by drix00** [comment]
Following an offline communication with @ppinard I share an example of hdf5 results file for mcxray. The format was quickly done and not all results is included and almost no options are included. You can download it on Dropbox:
https://www.dropbox.com/s/jtw13x396ix24ym/SimulationHDF5.hdf5?dl=0

The main feature I found important or good (or a good starting point) are:

- Multiple simulation results included in the same file
- Unique group name for each simulation base on the varied and fix parameters (the default option are not included)
    - this allow to copy other simulation in the same hdf5 file
    - the same varied and fix parameters are given as attribute of the simulation group
- Each result type is in a separate group. For mcxray it is the same name of the result file
- If the results is just a number, it is given as attribute
- If the result contain multiple values a dataset is used
    - each dimension of the dataset have a label and a dimension scale associate to it (with unit if appropriate)

The balance between subgroup or large dimension dataset are difficult to decide (which explain why the mcxray example is not consistent). Subgroups allow to clearly find/see the data using the hdfview and in the code, but it make more difficult to parse the file and copy a lot of data. Large dataset are not easy to view in hdfview and the code is obscure with a lot of indices to get a value, but it is easier to parse with generic code and copy/analyze large dataset.

We need to test with our first user case and see how it affect pymontecarlo and each Monte Carlo application project like pymontecarlo-casino2.

**Comment by ppinard** [comment]
Here is the first crack at saving options and results with HDF5:
https://www.dropbox.com/s/qniu3i8s8ue1zwx/project.h5?dl=0

I think it is the simplest mapping from the internal class structure in pymontecarlo and a structured HDF5 file. The associated code to create this "project" is located [here](https://github.com/pymontecarlo/pymontecarlo/blob/emas2017/pymontecarlo/testcase.py#L267) and all the code to generate an HDF5 file is in the package [pymontecarlo.fileformat](https://github.com/pymontecarlo/pymontecarlo/tree/emas2017/pymontecarlo/fileformat).

**Comment by drix00** [comment]
Good work!
I have some questions and comments on the HDF5 file format.
For me one big advantage of the HDF5 file is you can give it to someone and let him figure out how to get the information just by looking at the file (with the HDFView program for example).

Right now the name of each simulation is a uuid4, which does not have a meaning for the user (I am not sure if pymontecarlo need it also). Maybe we should think about a naming pattern for the group name representation each simulation. The uuid4 can be added as attribute if needed. Even just the basic pattern "Simulation #", i.e., "Simulation 1", "Simulation 2", "Simulation 3", ... is better for the user. Idem for some of the group that have "Name [id]" pattern. Could you comment on why they need the id in the name?

For the result, the information in the HDF5 file should not be repeated. You should provide a link to the detector and not recreate a PhotonDetector group in the results section (Also you have the same information, but different id). I need to think more about the way the HDF5 link with the x-ray transition and the intensity. Again it seem repetitive. K-L2 transition, will always have the same quantum numbers so a link to a transitions with quantum numbers matrix could be better. Idem for Copper transition list, it should not change too much.

As a side note on the x-ray transition, I think a separate project under openMicroanalysis is a better approach as other program can also use it and pymontecarlo just need to copy the transition he need from the reference HDF5. Furthermore, other program can also use it and start to have an uniform nomenclature in HDF5 file. I have a skeleton project on github [xray-nomenclature](https://github.com/drix00/xray-nomenclature) toward that goal. Let me know if you want me to work on it to be useful to pymontecarlo.

**Comment by ppinard** [comment]
Thank you for the comments. Answers below.

> Right now the name of each simulation is a uuid4, which does not have a meaning for the user (I am not sure if pymontecarlo need it also). 

There is no reason. It was an easy way to ensure that each simulation has a different name. The id is not used anywhere except that a folder is created using this id to store the simulation results from the MC codes (e.g. .cas). 

I have no problem to generate a simulation specific name, although the name itself might become quite long. 

> Could you comment on why they need the id in the name?

Because HDF5 does not allow two subgroups to have the same name. There is nothing preventing two materials to have the same `name` attribute or an option to have two `PhotonIntensityAnalysis`.

> You should provide a link to the detector and not recreate a PhotonDetector group in the results section (Also you have the same information, but different id).

I will fix this. 

>  I need to think more about the way the HDF5 link with the x-ray transition and the intensity. Again it seem repetitive.

I agree but I don't know where to save the xray line definitions. In the project root?

- project.h5
  - simulations
  - xraylines

The "avoid repetition" concept could also be extended much further, since the same materials, beam, detector, etc. could be reused in several simulations. I don't know if we should list all of them in the project root and only used references for the simulations. Any thoughts?

> I have a skeleton project on github xray-nomenclature toward that goal. Let me know if you want me to work on it to be useful to pymontecarlo.

I didn't know you had a project for this. I think the project [pyxray](https://github.com/openmicroanalysis/pyxray) already answers this. The best way is to install it through pip: `pip install pyxray` since it will come with the SQLite database containing the different nomenclature and properties of X-rays. Take a look at the functions `pyxray.xray_transition_notation` and `pyxray.xray_transitionset_notation`.

**Comment by ppinard** [comment]
Implemented in version [1.0](https://github.com/pymontecarlo/pymontecarlo/releases/tag/1.0.0). All options, results and settings are saved in a HDF5 file.
