### ISSUE TITLE
Immutable options and parameters

### ISSUE THREAD

**Issue by ppinard** [pymontecarlo/pymontecarlo#23]
It is important that once a simulation was executed, that its options cannot be modified. It is currently done by the concept of **freezing**. I think the whole structure of pymontecarlo could be simplified if the *Options* class and all its components (e.g. beam, sample, detectors, limits, etc.) would be immutable. To prevent having too many arguments in the `__init__` we could create *Builder* classes instead. While complete immutability is difficult to implement in Python, I would propose to either use the metaclass trick of pyxray ([pyxray.cbook.Immutable](https://github.com/ppinard/pyxray/blob/sql/pyxray/cbook.py#L14)).

**Comment by ppinard** [comment]
@drix00 said:
Can you give an example why the Options class need to be immutable? I understand we need a way to tell in the hdf5 file if the option associate with a results change (with a check sum maybe). But I never have to worry in the code about the Options class changing during the simulation or after.

**Comment by ppinard** [comment]
I think it is important that an _Options_ is validated before being run by a MC program. It would be frustrating to setup some options and then realized that they cannot be run. My idea was therefore that an _Options_ is validated upon its construction (i.e. in the `__init__(...)`) and is never changed afterwards. Something like this:

```python
class Options:

    def __init__(self, program, beam, sample, ...):
        self.program = program
        self.beam = program.converter.convert_beam(beam)
        self.sample = program.converter.convert_sample(sample)
        ...
```

I guess the other way would be to add a method `validate()`, but that would mean that each _Beam_, _Sample_, _Detector_ should also take a `program` object in order to validate their parameter.

**Comment by drix00** [comment]
At the end, each program need to validate the option before doing the simulation (or just crash). I also like the pythonic philosophy to let the user do what they want (and crash in the wall sometime). 

Is the class Options is for all programs using inheritance  or it is pymontecarlo options and the program have to "translate" into is own options? The later could be easier to implement for pymontecarlo, but harder for each program projects. Also it could solve the problem that some program option are not define in pymontecarlo and the program use is default value. In the other direction, if the program cannot "translate" the option, it just cannot do the simulation and does not do it (need to notify "range of options" and "analyze", see issue #21).

**Comment by ppinard** [comment]
It was decided not to make the new `Options` class immutable. Instead `Options` and its content (e.g. `Beam`, `Sample`, etc.) are all mutable and implemented with simple Python attributes. The validation and conversion of necessary attributes for a particular program is handled by the `Validator` class. This way the options classes are as simple as possible.
