### ISSUE TITLE
Run CASINO from command line

### ISSUE THREAD

**Issue by ppinard** [pymontecarlo/pymontecarlo#32]
It would significantly simplify the integration of Casino 2 if a simulation could be started from the command line, like for WinX-ray.

**Comment by drix00** [comment]
Casino 2 already support the command line:

`wincasino2_64.exe -batch "..\..\testData\testC.sim" "..\..\testData\Al_E3keV.sim"`

Let me know if it does not work or have problem with it.

**Comment by ppinard** [comment]
Is it possible that the version on the [website](http://www.gel.usherbrooke.ca/casino/download2.html) doesn't have this batch feature? I tried on Windows 10 and Casino UI appears but no simulation is running.  I however found a version on my computer where the batch works. The zip file was called "CASINO_v2.4.8.1_batch.zip".

**Comment by drix00** [comment]
I need to do a release of this version. To test/develop you can use this prerelease file:

https://www.dropbox.com/s/2acsajs12l8kyd5/CASINO_v2.5.0.0.zip?dl=0

I need to do more tests and document the new features (and the old one also) before doing a official release, but you can use it and report problem.

**Comment by ppinard** [comment]
For some reasons, the casino version in the last comment does not work with Wine. However, I found an older "Casino 2.48 + batch" version that you (@drix00) sent me which works. I uploaded it:

https://www.dropbox.com/s/gm72m8g6ryxypjr/casino2_batch.zip?dl=0

Were there many major changes between 2.4.8 and 2.5.0?

**Comment by drix00** [comment]
The main difference are the old one was build with Visual Studio 2010 and the new one with Visual Studio 2015 and added the Boost library. I did not find anything on Wine and the version of Visual Studio except older application are more likely to work on Wine. I will check if I can make it run with Wine.

**Comment by ppinard** [comment]
I might not have the latest wine version. Let me try this first before doing any changes.

For the time being, are there major differences between 2.4.8 and 2.5.0 from the point of view of pymontecarlo?

**Comment by drix00** [comment]
I did try on wine version 1.6.2 today. Strange thing CASINO v3 (only the 32 bit version, 64-bit have graphic problem) work with wine and not CASINO v2 with the same compiler. The error is because a function is not implemented in wine.

> Unhandled exception: unimplemented function KERNEL32.dll.WakeAllConditionVariable

Which is related to windows thread. I think casino v2, use windows thread and casino v3 boost thread. It could be the problem.

I will try to find the difference between the two projects and also test if compiled with Visual Studio 2017 work on wine. If it is not working, I can try to compile version 2.5.0 with Visual studio 2010.
 
The problem using the 2.4.8 version is that I cannot modify the intensity like discussed in https://github.com/drix00/pycasinotools/issues/4 and probably does not work if I compile with Visual Studio 2015.

**Comment by ppinard** [comment]
Thank you for the detailed diagnostics. Hopefully, Visual Studio 2017 fixes the problem.

**Comment by drix00** [comment]
I got a new version of CASINO 2 that work on Linux using Wine.
https://www.dropbox.com/s/o8sbwb3j643ui3s/CASINO_v2.5.0.0.zip?dl=0
Can you test it and confirm it work also for you.
I will do the modification mentioned in https://github.com/drix00/pycasinotools/issues/4 and test CASINO than do a release.

The solution is to compile CASINO to be compatible with windows XP. It seem that if you can run you program on XP, it will work also with Wine. The problem with the previous version was that the boost 1.60 log library was not linking correctly when targeting windows XP. Boost 1.63 work correctly when targeting windows XP.

**Comment by ppinard** [comment]
I confirm that it also works for me. Here would be the deb:
https://www.dropbox.com/s/hevcr4t9sk8lav0/casino2_2.5.0.0-1_amd64.deb?dl=0

**Comment by ppinard** [comment]
CASINO 2 was tested on Windows, MacOS and Linux and it works perfectly.
