### ISSUE TITLE
User interface

### ISSUE THREAD

**Issue by ppinard** [pymontecarlo/pymontecarlo#33]
I sketched what I think the wizard to create new simulations should look like. The sketches are SVG files created using [Inkscape](https://inkscape.org/en/). They are located in the folder [sketch](https://github.com/pymontecarlo/pymontecarlo/tree/sketch/sketch) of the branch [sketch](https://github.com/pymontecarlo/pymontecarlo/tree/sketch). Comments are more then welcomed.

1. Select type(s) of analysis

![newsimulation_analysis](https://cloud.githubusercontent.com/assets/715280/21751275/99f30a2a-d5bc-11e6-8239-c967a1c8d439.png)

All types of analysis should be listed here. We might think of a way to categorize them if there are too many.

2. Define sample

![newsimulation_sample](https://cloud.githubusercontent.com/assets/715280/21751295/1355e7f2-d5bd-11e6-8737-cf5a54e1bd5b.png)

The user first must define some materials (composition and density). Secondly, the user selects a type of geometry from the drop down menu. For the current example, material(s) are associated to each horizontal layer with one or more thicknesses. Note the preview button, where the selected geometry should be displayed in a 2D or possibly 3D plot, with the x, y and z axes. It should be possible to load/save the list of materials and the complete sample.

3. Setup incident beam

![newsimulation_beam](https://cloud.githubusercontent.com/assets/715280/21752044/5cb649ee-d5c9-11e6-9f44-07d577a5c18f.png)

The user selects a type of beam (Gaussian, pencil, raster) from the drop-down menu and other properties such as the initial energy. The next step is to define the beam positions. This is down by selecting a type of pattern (single point, line scan, grid of points). The preview button should display the sample and the beam positions.

4. Select program(s)

![newsimulation_program](https://cloud.githubusercontent.com/assets/715280/21752063/ed460a6c-d5c9-11e6-9a2f-80b6f3aad573.png)

Select the program for the simulations. In this example, where a multi-layer sample was selected, WinX-Ray is not available since it does not support this type of sample.

5. Setup simulation limit

![newsimulation_limit](https://cloud.githubusercontent.com/assets/715280/21752081/297aad6c-d5ca-11e6-8707-57e3d156a3a4.png)

Setup the simulation limit for each program. Each program can have different limits.

6. I think the next pages should be for 

 - parameters related to the selected analyses (e.g. take-off angle of X-ray detector, which standards for k-ratios)
 - advanced parameters for the Monte Carlo programs (e.g. models, interaction forcings)

**Comment by drix00** [comment]
Are this dialog for only one simulation? It seem some options are for multiple simulation. From my experience using mcxray in our group. The user start with either 1 simulation (and normally use the program itself) or have 1 to 3 parameters he want to vary. More than 3 parameters the number of simulations become to much to be reasonable to simulate and the user need to be careful of the range of each parameter. Maybe we should have two path in the interface:

1. The user want to do one simulation and get the results selected (as shown in the Select type(s) of analysis dialog)
2. The user want to vary 1 to X parameters and get the selected results for all of them.

To give a concrete example:
I have two phase Zircon and Fergusonite and want to calculate the electron and x-ray ranges in both of them for three energy: 5, 10, and 20 using all the simulation programs. So I do these steps:

1. Select _multiple simulation wizard_
2. Add material parameter: Zircon and Fergusonite (just the name, composition added later in another dialog)
3. Add accelerating voltage parameter: 5, 10, 20 (as a list)
4. Add simulation program parameter: list of all available
5. Click OK (before clicking OK this dialog can give the total number of simulations, so the user can change the range of the parameter or remove parameter from the list or also incompatible program with the chosen parameters)
6. Select which result I want: electron and x-ray ranges
7. Now pymontecarlo will display all the parameter dialog I need to create the simulation for the varied parameters: composition of Zircon and type of sample (bulk),  idem for Fergusonite; beam options, but without the energy option or gray out; limit of the simulation. This two last steps (6 and 7) are also the _one simulation wizard_

Before starting creating the input file for each program, have the option to save the "experiment" and load it later. Changing the "varied parameters may invalidate some other options and need to be redefine". With mcxray script, it just ignore the now invalid parameter, but it was not robust and most of the time it was better to delete everything and redo it. For a first (or second) implementation, we could just invalidate the options and results (already simulated), but later we could refine the implementation to "recycle" the valid options and results.

To resume I think we have three layers or leafs at the same level, but the one below depend on the layer(s) above:

1. Variate parameters
2. Option of one simulation, which include the result to be extracted for each simulation
3. Results extracted from the simulations with graphic (if possible of each result versus each variate parameter)

I am not sure my comment is clear. I will try to have a sketch of the dialog later (but I am terrible at drawing).

Also maybe we should pick up one analysis to do (it could be my example) and start the implementation to be able to do it and see what is not correct and need rethink. Again it was my experience with mcxray, to refine the scripting for each new analysis, but we need to do a better job in the implementation. I was doing mostly patching and not good refactoring.

**Comment by ppinard** [comment]
I do not know if we really need different wizard for "one simulation" and "multiple simulation". All parameters that could be varied should be available to the user. These were not specifically shown in the sketches but I was thinking to follow the philosophy of the current *pymontecarlo* version. Labels in blue can be varied by either entering a list of values or using a range "à la Python" (`start:stop:step`).

 > More than 3 parameters the number of simulations become to much to be reasonable to simulate and the user need to be careful of the range of each parameter.

I agree but that's why we should show the total number of simulations. It was there in the current version, but I will readded to the sketches.

> 2. Add material parameter: Zircon and Fergusonite (just the name, composition added later in another dialog)

Why should the user only defined the name? I think it would make sense that the define materials are maybe automatically saved for later use or many a list of recent materials...

> 6. Select which result I want: electron and x-ray ranges

My idea of select first the type of result(s) is that it allows us to adapt the wizard based on that selection. For instance, if a result is only avaible with one Monte Carlo program or if we do not need to specify an X-ray detector. I might be wrong but I think the users know more than anything else what they are expecting from the Monte Carlo simulations. They are doing simulations for some reasons or it should be the first thing they decide.

> Before starting creating the input file for each program, have the option to save the "experiment" and load it later.

I completely agree.

> For a first (or second) implementation, we could just invalidate the options and results (already simulated), but later we could refine the implementation to "recycle" the valid options and results.

To recycle old simulations is an interesting idea. My only question is how can we tell that a simulation with the same options was already simulated? Should the simulation options implement `__eq__`?

> Results extracted from the simulations with graphic (if possible of each result versus each variate parameter)

This is a complicated but important point. Maybe we should sketch what the results display should look like.

> Also maybe we should pick up one analysis to do (it could be my example) and start the implementation to be able to do it and see what is not correct and need rethink. 

Good idea. Should we start with only X-ray range, i.e. depth of the PRZ?

**Comment by ppinard** [comment]
I would change my last comment and suggest we first start with an interface to simulate k-ratios (with simulations for standard and "unknown").

**Comment by ppinard** [comment]
The user interface was modified in version [1.0](https://github.com/pymontecarlo/pymontecarlo/releases/tag/1.0.0), reflecting on the ideas mentioned in this post. There is obviously space for other improvements, but these should be handled by separate issues.
