### ISSUE TITLE
Preview of sample geometry

### ISSUE THREAD

**Issue by ppinard** [pymontecarlo/pymontecarlo#34]
As shown in #33, pymontecarlo should allow users to preview the generated sample. The same preview capabilities should also be later used to visualize the electron trajectories. Although a 3D preview of the sample geometry is more eye-catching, the samples currently available in pymontecarlo do not require 3D for their comprehension. I propose to design a 2D preview where the sample can be viewed from different perspectives. I would summarize the requirements as follows:

1. Support all currently implemented samples (substrate, inclusion, horizontal layers, vertical layers and sphere)
2. Display XY, XZ, YZ perspectives
3. Display coordinate system
4. Display the sample sub-structures (e.g. layers) and the materials used (2 modes)
5. Allow zooming and panning
6. Save one or many perspectives to disk in a vector-based file format (e.g. svg, pdf)
7. Display intersection of electron beam with sample (i.e. initial beam positions)
8. Display electron trajectories and/or collisions. Allow different colors for backscattered, transmitted and absorbed electrons.

**Comment by 0b11001111** [comment]
> 5. Allow zooming and panning
> 6. Save one or many perspectives to disk in a vector-based file format (e.g. svg, pdf)

We could offer these functions by adding matplotlibs navigation toolbar. Is that okay or do you want me to move these functions into native qt widgets/dialogues?

Where do you want me to implement this? Where are the dialogues **build sample** and **incident beam** located? Where will the results be displayed? 

Once I had a closer look on your code and understood its design I'll make a plan about how to structure the preview feature and we'll discuss it here.

**Comment by ppinard** [comment]
> We could offer these functions by adding matplotlibs navigation toolbar. Is that okay or do you want me to move these functions into native qt widgets/dialogues?

Matplotlib is perfect. 

> Where do you want me to implement this? Where are the dialogues build sample and incident beam located? Where will the results be displayed?

I created a branch [preview](https://github.com/pymontecarlo/pymontecarlo/tree/preview) with a template for the preview in `pymontecarlo.figures.sample`. Before thinking about dialogues and GUI, I think we should have a class that takes arguments such as a *Sample*, some *Beam* and in the future trajectories and draws them in a matplotlib Axes object. If this works we can then integrate it easily in the GUI.

**Comment by 0b11001111** [comment]
I checked out your example and some questions appeared:

Some geometrical information I need comes with the samples like layer thickness, other don't like substrate dimensions. Also, positioning seems to be a bit tricky since samples and beams don't know each other.
My idea is to introduce new classes `SampleFigure(Figure)`, `BeamFigure(Figure)` and `TrajectoryFigure(Figure)` which contain a position and size information if necessary. On top of that there could be a compositor class which arranges the setup and, if available, data. What do you think?

Furthermore there seems to be no scheme for colouring the materials. Should I use just random pleasant colours?

**off topic**
Whenever I work with matplotlib and run the debugger there's no graphical output and the application terminates without considering breakpoints. Is there any technical reason for that? I couldn't find a satisfying answer for that online.

**Comment by ppinard** [comment]
It is a good idea to separate into `SampleFigure(Figure)`, `BeamFigure(Figure)` and `TrajectoryFigure(Figure)`. 

> Also, positioning seems to be a bit tricky since samples and beams don't know each other.

I don't quite understand your point here. The position of every sample in space is clear. The substrate has a XY plane at Z=0. The inclusion is a half sphere centered at (0, 0, 0) inside a substrate. The horizontal layer sample is a series of XY plane where the first one is at Z=0 and going towards negative Z. The vertical layer sample is a bit more complicated. The surface is a XY plane at Z=0 and each vertical layer is a YZ plane at a certain X. The X position of the planes depends on the number and thickness of planes. See the property [layers_xpositions_m](https://github.com/pymontecarlo/pymontecarlo/blob/preview/pymontecarlo/options/sample/verticallayers.py#L53) for help.

As for the beams, they are positioned in the same reference frame.

> Furthermore there seems to be no scheme for colouring the materials. Should I use just random pleasant colours?

Yes. I think the only issue is two adjacent materials should have differentiable colours. Maybe there is away to ensure this in the random colour generator...

> Whenever I work with matplotlib and run the debugger there's no graphical output and the application terminates without considering breakpoints. Is there any technical reason for that?

I never used the debugger and matplotlib. Is it possible that matplotlib runs in a different thread...

**Comment by ppinard** [comment]
The second answer might help with the colours:
http://stackoverflow.com/questions/470690/how-to-automatically-generate-n-distinct-colors

**Comment by 0b11001111** [comment]
> I don't quite understand your point here. [...]

Me neither when I look back but thanks for your answer, it helped me elsewhere.

I've implemented the XZ views for almost all samples and Gaussian beam. What is the difference of a SphereSample and an InclusionSample? Another question that arose is about how to select the sector that's displayed? 

Once I've implemented `_draw_sample_sphere` I'll push my solution and we can discuss about the design. Support for tilts and YZ/XY view will be added after that.

I also fixed some bugs in the sample implementations https://github.com/pymontecarlo/pymontecarlo/commit/7cd9e1bd2c0f4ea85a10c9ec559e5147262658f8

**Comment by ppinard** [comment]
> What is the difference of a SphereSample and an InclusionSample?

![inclusion_vs_sphere](https://cloud.githubusercontent.com/assets/715280/22865108/24b9c406-f155-11e6-87eb-647ffb971f92.png)

> Another question that arose is about how to select the sector that's displayed?

For the moment I would always assume that the other coordinate is fixed at 0. For instance, in the XZ view, Y is always equal to 0.

> Once I've implemented _draw_sample_sphere I'll push my solution and we can discuss about the design. Support for tilts and YZ/XY view will be added after that.

Sounds good!

> I also fixed some bugs in the sample implementations 7cd9e1b

Yes I saw. Thank you. I merge it down to emas2017 (commit 7273bbb).

**Comment by 0b11001111** [comment]
Okay, I just committed (https://github.com/pymontecarlo/pymontecarlo/commit/cecba6a986725e733d5013af575a864d2d1020ff) a very first version of my implementation.

I integrated the plot into a simple QDialog and it works pretty good so far.  

Just let me know if you need further explanation or want to discuss some aspects.

Next steps will be:
* **tilt support** (I'm thinking about subclassing patch or using pathpatch to solve that)
* **XY/YZ view**
* fancy color gradient to visualize intensity distribution of gaussian beam (optional)

**Comment by ppinard** [comment]
The implementation looks good. I added a few comments using the GitHub line comment. You can see them online on the commit page cecba6a. It is the first time I use this, so please let me know if you find this method of commenting useful.

Regarding your next step:

1. tilt support

All matplotlib `Artist` have a `set_transform(...)` method. It works on `Patch` if the `Patch` is in a `PatchCollection`. I think this can solve the tilt / rotation problem.

```python
from matplotlib.patches import Rectangle
from matplotlib.collections import PatchCollection
from matplotlib.transforms import Affine2D
import matplotlib.pyplot as plt

fig = plt.figure()
ax = fig.add_subplot("111")

rect = Rectangle((0, 0), 2, 1)

t = Affine2D().rotate_deg(15)
rect.set_transform(t)

collection = PatchCollection([rect])
ax.add_collection(collection)

ax.set_xlim(-5, 5)
ax.set_ylim(-5, 5)

plt.show()
```

3. fancy color gradient to visualize intensity distribution of gaussian beam (optional)

As mentioned in my comment, this is very optional.

**Comment by 0b11001111** [comment]
> The implementation looks good. I added a few comments using the GitHub line comment. You can see them online on the commit page https://github.com/pymontecarlo/pymontecarlo/commit/cecba6a986725e733d5013af575a864d2d1020ff. It is the first time I use this, so please let me know if you find this method of commenting useful.

Depends. If the issues are meant to be some kind of documentation of our decisions it's better to discuss it here I'd say. If the discussion is spread over several files and commits it'll be quite difficult to retrace it.
Actually I like that feature. Let's use it for smaller issues and discuss all the major stuff here while referring to the commit.

![img_20170216_184107](https://cloud.githubusercontent.com/assets/19192307/23033435/5199a72c-f478-11e6-834c-d0b4c6b6bb46.jpg)
I can't see how to achieve the second using `set_transform(...)` but I'm also not sure if my interpretation of tilt is right.

**Comment by ppinard** [comment]
Here is how the tilt looks like

![img_20170219_185154](https://cloud.githubusercontent.com/assets/715280/23105324/6ddebfe4-f6d5-11e6-9ef1-5d41bc53b789.jpg)

and how to achieve this with set_transform:

```python
from matplotlib.patches import Rectangle
from matplotlib.collections import PatchCollection
from matplotlib.transforms import Affine2D
import matplotlib.pyplot as plt

fig = plt.figure()
ax = fig.add_subplot("111")

rect1 = Rectangle((-2, 0), 2, 3)
rect2 = Rectangle((0, 0), 1, 3)
rect3 = Rectangle((1, 0), 2, 3)

t = Affine2D().rotate_deg(30)
rect1.set_transform(t)
rect2.set_transform(t)
rect3.set_transform(t)

collection = PatchCollection([rect1, rect2, rect3])
collection.set_color(['b', 'g', 'r'])
ax.add_collection(collection)

ax.set_xlim(-5, 5)
ax.set_ylim(-5, 5)

plt.show()
```

**Comment by 0b11001111** [comment]
Okay, that makes sense. Samples have two parameters which I interpret as the following:
* **tilt_rad**: Angle between **X** and substrate within **XZ** plane while 0.0 means the substrate is _parallel_ to Z axis
* **rotation_rad**: Rotation within the **XY** plane while 0.0 means the substrate is _parallel_ to X and orthogonal to Y axis

Is that right?

Furthermore I do not fully understand the concept behind `*.set_transform`. Your example works like expected but when I use `collection.add_transform(t)` the canvas keeps blank. When I initialize the transformation like `t = ax.transData + Affine2D().rotate_deg(30)` (like in [this ](http://stackoverflow.com/questions/4285103/matplotlib-rotating-a-patch)example) I get this:

![bildschirmfoto vom 2017-02-27 20-43-44](https://cloud.githubusercontent.com/assets/19192307/23376716/8167fd4c-fd2d-11e6-8115-e18118e4777b.png)

... which is not what I expected at all.

I could solve it as you showed me but we could also safe some redundancy if the rotation is done in the `_draw_sample` method.

**Comment by ppinard** [comment]
Any rotation in 3D requires an axis and an angle. I defined the axis for *tilt* as **X** and the axis for rotation as **Z'**, where **Z'** is the **Z** axis after applying the tilt. A positive angle is a counter-clockwise rotation around these axes. At *tilt* and *rotation* equal 0.0, the substrate normal points towards **+Z**, or in other words, the substrate is a **XY** plane crossing the **Z** axis at `Z=0`. 

I think for simplicity for now you can ignore the *rotation*, i.e. the rotation around **Z'**.

As for matplotlib, I am not sure how the transformation works. I also saw that `collection.set_transform` does not work. On your stackoverflow link, many people are also puzzled in the comments.  Is there a problem of using `set_transform` on every patch?

**Comment by 0b11001111** [comment]
> Any rotation in 3D requires an axis and an angle. I defined the axis for *tilt* as **X** and the axis for rotation as **Z'**, where **Z'** is the **Z** axis after applying the tilt. A positive angle is a counter-clockwise rotation around these axes. At *tilt* and *rotation* equal 0.0, the substrate normal points towards **+Z**, or in other words, the substrate is a **XY** plane crossing the **Z** axis at `Z=0`. 

Thank you. This information should be available in the user dialogue to avoid confusion.

> [...] Is there a problem of using `set_transform` on every patch?

No, technically it's fine but I solved that anyway. Now I can perform the transformation in `_draw_sample` once and don't need to reimplement it for every sample.

**Comment by 0b11001111** [comment]
I've added support for perspectives (e7e3d2818e73529f092b278f633b9d2d9e1adfcb) which is realised as cross-section views at (X,Y=0,Z)/(X=0,Y,Z)/(X,Y,Z=0).

I also added rudimentary support for _tilt_ (7441b40cf92431d7c20e25815332dd21d5d9ed3d) which uses `Affine2D().scale` and `Affine2D().rotate_around` to visualize its effect on cross-sections. This works most of the time but deviates from reality in certain cases (e.g. YZ perspective on a vertical layer sample).

**Comment by drix00** [comment]
Just to comment on the 3D sample viewer perceptive as I have explore the library available lately. For 3D display of sample and data. I have check MayaVi and the vtk (the library behind mayaVi) and  VPython.

- VPython is easy and powerful, but now only run in jupyter notebook and I did not find a way to run it in a python script. So out.
- MayaVi is very powerful and good doc. Sadly on windows run very slowly: 5 minutes to import mayavi at the start of the script. So out.
- VTK is powerful, but low level. The doc is minimum and not accurate, i.e., it is for the C++ code. Could be a solution, but a lot of work to understand the library.

For 2D I look at some SVG library, but most of them have problem with text display and some using long latex process to generate them. So I end up using powerpoint for a quick drawing of my sample.

My conclusion for 3D was to use openGL, the learning step at the start is large, but it work well and it is very powerful. CASINO 3 use it to display the sample and trajectories. Also it would work for 2D display.

**Comment by ppinard** [comment]
Interesting information about the different libraries. For the moment, matplotlib seems to give decent results for 2D and we benefit from all the built-in functionalities (pan, zoom, save to different formats). In a second iteration, we should definitely look at OpenGL.

**Comment by ppinard** [comment]
The perspective and tilt looks good. Maybe it would be good to add some unit tests, at least to test the main functionalities.

One point that should be corrected is the assigned colors. Using `material.__repr__()` as the key is not a good idea. I would move the color selection inside the class and simply assigned a color to each material when `draw()` is called. You can use the property `materials` to get a list of all materials in a sample. The order of the materials in that list should not change unless the sample is changed (e.g. a new layer is added). That way you do not need a dictionary.

I merged your current "preview" branch into "emas2017". You should also merge "emas2017" into your "preview" branch to make sure you have all the latest updates.

**Comment by 0b11001111** [comment]
> The perspective and tilt looks good. Maybe it would be good to add some unit tests, at least to test the main functionalities.

It's on my to do list

> One point that should be corrected is the assigned colors. Using `material.__repr__()` as the key is not a good idea. [...]

What else should I use? Material is not hashable and does not work as a key by itself.

> [...] I would move the color selection inside the class and simply assigned a color to each material when `draw()` is called. You can use the property `materials` to get a list of all materials in a sample. The order of the materials in that list should not change unless the sample is changed (e.g. a new layer is added). That way you do not need a dictionary.

I moved the functions into SampleFigure class and the color sets to an separate python file but I would like to keep the dictionary so we can give substrates shades of grey, layers shades of brown and so on. 

> I merged your current "preview" branch into "emas2017". You should also merge "emas2017" into your "preview" branch to make sure you have all the latest updates.

Done

**Comment by ppinard** [comment]
> I would like to keep the dictionary so we can give substrates shades of grey, layers shades of brown and so on.

`Material` cannot be hashed because it is mutable. Use a name or repr won't work either, because `Material` is mutable. See [Python doc](https://docs.python.org/3.5/reference/datamodel.html#object.__hash__): "If a class defines mutable objects and implements an `__eq__()` method, it should not implement `__hash__()`, since the implementation of hashable collections requires that a key’s hash value is immutable (if the object’s hash value changes, it will be in the wrong hash bucket)." 

If you want to use different colours for the substrate, layers, etc. then you can assign the colours specifically for each type of sample. I really do not understand why you need a dictionary.

**Comment by 0b11001111** [comment]
Okay, I added a mechanism that automatically selects sane values for axis' limits and also added some unit tests.

Is any feature missing or can we start integrating it into the main application?

**Comment by 0b11001111** [comment]
**Coloring**
My requirements for coloring are:
* unique (if possible) color for any material
* different color sets e.g.:
    * substrates have shades of grey
    * layer materials have shades of brown
* keep color for materials over `SampleFigure`'s life cycles (I think that's important because users could be confused otherwise)

For the last point I need some key value pairs to store selected colors. How likely is it that two different Materials have the same string representation? If that happens only once in a few dozen times I think it's okay for now.

**Comment by ppinard** [comment]
I propose that I have a look at the code so I can understand the problem and constraints.

**Comment by ppinard** [comment]
I had a look at the code and I thought it makes more sense to define the color of a material in the `Material` class. That way users can customize the color as they wish and we do not need a dictionary to store the color. By default, one of the color of the brown color set is used.

I also made the following modifications:

- Move Qt code to `pymontecarlo_gui`
- Use an `Enum` for the perspective, which is now an attribute
- Use methods in a `dict` to calculate the view size, like the draw methods for the samples and beams
- Fix so all tests pass

I would be ready to merge, unless you can think of other modifications.

**Comment by 0b11001111** [comment]
> I would be ready to merge, unless you can think of other modifications.

Nope, for now I think that's it.

**Comment by ppinard** [comment]
It is now merged in emas2017. We can reopen the issue when/if we need the trajectories.
