### ISSUE TITLE
Bug!?

### ISSUE THREAD

**Issue by 0b11001111** [pymontecarlo/pymontecarlo#36]
There is a bug occurring when I try to launch my SampleFigure script for example (or any other code which uses pyMonteCarlo). Did I just messed up my local repository or is it a bug in our code?

[Here's my error log](https://github.com/pymontecarlo/pymontecarlo/files/888658/log.txt)

**Comment by ppinard** [comment]
Why do you have the project "pymontecarlo-cli" in your path? Can you do "from pkg_resources import iter_entry_points" in the Python shell?

**Comment by 0b11001111** [comment]
Okay, I uninstalled _pyMonteCarlo-CLI_ and now it works, not sure why I installed it at all. `from pkg_resources import iter_entry_points` worked anyway.
