### ISSUE TITLE
Incident Beam

### ISSUE THREAD

**Issue by 0b11001111** [pymontecarlo/pymontecarlo#37]
I recently pushed a version of the `BeamWidget` and `BeamPositionWidget` (https://github.com/pymontecarlo/pymontecarlo-gui/commit/febfe722086e5de2bcf11079cebca77d53eab451) where I implemented everything I was able to.

**BeamWidget**
* `beams(self)` is supposed to return a list of beams but we only set up one. What's the idea behind that function?

**BeamPositionWidget**
* What is the _Edit_-Button supposed to do? Does is modify a certain position or a whole scan?
* How can I make `QTableView`'s content width make fit the view?
* Currently I use text to describe a pushbutton's functionality but I want to use icons as in your sketch. Does Qt already ships some default icons or where can I get them from?

**Comment by 0b11001111** [comment]
Okay, for now everything is working. Please take a look and tell me your thoughts. My questions from above are still open except the _Edit button_ thing. Especially `BeamWidget.beams(self)` is quite unclear to me.

I decided to add an additional list view so the user can browse scans separate. 

![bildschirmfoto vom 2017-04-22 23-57-57](https://cloud.githubusercontent.com/assets/19192307/25308564/8c08c132-27b7-11e7-951d-8e34ee1c7557.png)

**Comment by ppinard** [comment]
Implemented in version [1.0](https://github.com/pymontecarlo/pymontecarlo/releases/tag/1.0.0)
