### ISSUE TITLE
Branch v0.1.0 should be deleted

### ISSUE THREAD

**Issue by drix00** [pymontecarlo/pymontecarlo#49]
The branch v0.1.0 does not seem to be used anymore. It should be deleted, but the branch have 3 commits ahead so they should be reviewed and maybe merged with master branch.

When the commits are reviewed the branch can be deleted with this command:

`git push origin --delete v0.1.0`

**Comment by ppinard** [comment]
The 3 commits are no longer pertinent. I deleted the branch.
