### ISSUE TITLE
h5py-numpy incompatibility

### ISSUE THREAD

**Issue by 0b11001111** [pymontecarlo/pymontecarlo#55]
h5py currently struggles with current numpy version 1.14 but 1.13.* is fine as described in [this](https://github.com/h5py/h5py/issues/969) issue. pyMonteCarlo may enforce a older version until they have solved that.
```
(env_auto) [vm-user@localhost scripts]$ python simulation_simple.py 
/home/vm-user/Workspace/pymontecarlo_test/env_auto/lib64/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
```

**Comment by ppinard** [comment]
It is a future warning. I don't think we need to worry about this. I am sure it will be fixed by h5py.
