### ISSUE TITLE
understanding OptionsBuilder

### ISSUE THREAD

**Issue by 0b11001111** [pymontecarlo/pymontecarlo#59]
I ran into a situation I don't fully understand. Given the following code

``` Python
from pymontecarlo.options.analysis.kratio import KRatioAnalysis
from pymontecarlo.options.beam.gaussian import GaussianBeam
from pymontecarlo.options.detector import PhotonDetector
from pymontecarlo.options.material import Material
from pymontecarlo.options.options import  OptionsBuilder
from pymontecarlo.options.sample import VerticalLayerSample
from pymontecarlo.options.sample.base import Layer
from pymontecarlo_casino2.program import Casino2Program

ob = OptionsBuilder()
ob.add_program(Casino2Program(number_trajectories=100))
ob.add_analysis(KRatioAnalysis(PhotonDetector('myPhotonDetector', math.radians(40.),
                                              math.radians(0.))))
ob.add_beam(GaussianBeam(energy_eV=15e3, diameter_m=0.))
ob.add_sample(VerticalLayerSample(left_material=Material.pure(26),
                                  right_material=Material.pure(26),
                                  layers=[Layer(Material('MnS', {25: 0.6316, 16: 0.3685}), 50e-9),
                                          Layer(Material('NiP', {28: 0.6546, 15: 0.3454}), 50e-9)]))

print(ob.build())
```

I get a list of **six** *Options* but not **one** as I would expect. As I understand a *OptionsBuilder* should return a list of all possible combinations of given attributes which is 1x beam, 1x sample and 1x analysis (1x1x1=1) in my case.

Is that the expected behaviour and if so, why?

**Comment by ppinard** [comment]
It is because you selected a KRatioAnalysis. It automatically create Options for the standards required to calculate k-kratios.

**Comment by 0b11001111** [comment]
Okay, now I see. Five of them simulate a pure substrates used to compute the standards, just as many as materials used in my sample. But how does _KRatioAnalysis_ know of them? If I create an _Options_ instance manually with the same properties as in my sample it works just fine. Where does it get the standards from in this case? Is there a central registry being updated once I simulate those options?

**Comment by ppinard** [comment]
See add_standard_material method of KRatioAnalysis class.

**Comment by ppinard** [comment]
@luoc0815 was this question answered?

**Comment by 0b11001111** [comment]
It was!
