### ISSUE TITLE
ProgramMock

### ISSUE THREAD

**Issue by 0b11001111** [pymontecarlo/pymontecarlo#68]
In order to fake simulations for testing I tried to subclass `ProgramMock` and `WorkerMock` with a custom `run` method in my `WorkerMock` sub class. It did not work at all.

What I wanted to achieve was a fake simulation which produces some results depending on the input options instead of static results or no results like existing mock classes do. Therefore it would be useful to insert a function at some point that takes `Options` as input and returns `Result` as output or modifies `Simulation` directly. E.g.:

``` Python
def fake_sim(simulation):
    x = simulation.options.sample.layers[0].thickness_m
    krb = KRatioResultBuilder(KRatioAnalysis(PhotonDetector('mydet', 0)))
    krb.add_kratio(((25, 'K-L3')), (x*1e8)^2, 1.)
    simulation.results.append(krb.build())
```

How can I achieve such behaviour without modifying several mock classes?

**Comment by ppinard** [comment]
I implemented a sort of fake simulation in pymontecarlo-reconstruction. See [ a4b42c1](https://bitbucket.org/epmaac/pymontecarlo-reconstruction/commits/a4b42c1e8ad8c84d05d977d0cbdb15283ff27096). I think this is too specific for pymontecarlo library.
