### ISSUE TITLE
Add reference information to cite pymontecarlo

### ISSUE THREAD

**Issue by drix00** [pymontecarlo/pymontecarlo#73]
Add a section in the github readme to how to cite pymontecarlo. I found this reference:
Pinard, P., Demers, H., Gauvin, R., & Richter, S. (2013). PyMonteCarlo: A Common Programming Interface for Running Identical Simulations using Different Monte Carlo Programs. Microscopy and Microanalysis, 19(S2), 822-823. doi:10.1017/S1431927613006107

Maybe add also reference of papers citing pymontecarlo.

Thanks,
Hendrix

**Comment by ppinard** [comment]
Done
